atrributes = {
  name = "Keyboard"
}

-- note that the id #s correspond to the keycodes as identified by the operating system... there is no rhyme or reason to them otherwise

controls = {
		{id = 0 , name = "a", minimum = 0, maximum = 1, expression = "" },
        {id = 1 , name = "s", minimum = 0, maximum = 1, expression = "" },
        {id = 2 , name = "d", minimum = 0, maximum = 1, expression = "" },
        {id = 3 , name = "f", minimum = 0, maximum = 1, expression = "" },
        {id = 4 , name = "h", minimum = 0, maximum = 1, expression = "" },
        {id = 5 , name = "g", minimum = 0, maximum = 1, expression = "" },
        {id = 6 , name = "z", minimum = 0, maximum = 1, expression = "" },
        {id = 7 , name = "x", minimum = 0, maximum = 1, expression = "" },
        {id = 8 , name = "c", minimum = 0, maximum = 1, expression = "" },
        {id = 9 , name = "v", minimum = 0, maximum = 1, expression = "" },
        {id = 10, name = "`", minimum = 0, maximum = 1, expression = "" },
        {id = 11, name = "b", minimum = 0, maximum = 1, expression = "" },
        {id = 12, name = "q", minimum = 0, maximum = 1, expression = "" },
        {id = 13, name = "w", minimum = 0, maximum = 1, expression = "" },
        {id = 14, name = "e", minimum = 0, maximum = 1, expression = "" },
        {id = 15, name = "r", minimum = 0, maximum = 1, expression = "" },
        {id = 16, name = "y", minimum = 0, maximum = 1, expression = "" },
        {id = 17, name = "t", minimum = 0, maximum = 1, expression = "" },
        {id = 18, name = "1", minimum = 0, maximum = 1, expression = "" },
        {id = 19, name = "2", minimum = 0, maximum = 1, expression = "" },
        {id = 20, name = "3", minimum = 0, maximum = 1, expression = "" },
        {id = 21, name = "4", minimum = 0, maximum = 1, expression = "" },
        {id = 22, name = "6", minimum = 0, maximum = 1, expression = "" },
        {id = 23, name = "5", minimum = 0, maximum = 1, expression = "" },
        {id = 24, name = "=", minimum = 0, maximum = 1, expression = "" },
        {id = 25, name = "9", minimum = 0, maximum = 1, expression = "" },
        {id = 26, name = "7", minimum = 0, maximum = 1, expression = "" },
        {id = 27, name = "-", minimum = 0, maximum = 1, expression = "" },
        {id = 28, name = "8", minimum = 0, maximum = 1, expression = "" },
        {id = 29, name = "0", minimum = 0, maximum = 1, expression = "" },
        {id = 30, name = "]", minimum = 0, maximum = 1, expression = "" },
        {id = 31, name = "o", minimum = 0, maximum = 1, expression = "" },
        {id = 32, name = "u", minimum = 0, maximum = 1, expression = "" },
        {id = 33, name = "[", minimum = 0, maximum = 1, expression = "" },
        {id = 34, name = "i", minimum = 0, maximum = 1, expression = "" },
        {id = 35, name = "p", minimum = 0, maximum = 1, expression = "" },
		{id = 36, name = "RETURN", minimum = 0, maximum = 1, expression = "" },
        {id = 37, name = "l", minimum = 0, maximum = 1, expression = "" },
        {id = 38, name = "j", minimum = 0, maximum = 1, expression = "" },
        {id = 39, name = "'", minimum = 0, maximum = 1, expression = "" },
        {id = 40, name = "k", minimum = 0, maximum = 1, expression = "" },
        {id = 41, name = ";", minimum = 0, maximum = 1, expression = "" },
        {id = 42, name = "\\", minimum = 0, maximum = 1, expression = "" },      
        {id = 43, name = ",", minimum = 0, maximum = 1, expression = "" },
        {id = 44, name = "/", minimum = 0, maximum = 1, expression = "" },
        {id = 45, name = "n", minimum = 0, maximum = 1, expression = "" },
        {id = 46, name = "m", minimum = 0, maximum = 1, expression = "" },
        {id = 47, name = ".", minimum = 0, maximum = 1, expression = "" },
        {id = 48, name = "TAB", minimum = 0, maximum = 1, expression = "" },
        {id = 49, name = "SPACE", minimum = 0, maximum = 1, expression = "" },
		{id = 50, name = "`", minimum = 0, maximum = 1, expression = "" },
        {id = 51, name = "DELETE", minimum = 0, maximum = 1, expression = "" },
        {id = 52, name = "ENTER", minimum = 0, maximum = 1, expression = "" },
        {id = 53, name = "ESCAPE", minimum = 0, maximum = 1, expression = "" },
		{id = 55, name = "CMD", minimum = 0, maximum = 1, expression = "" },
		{id = 56, name = "SHIFT", minimum = 0, maximum = 1, expression = "" },
		{id = 57, name = "CAPSLOCK", minimum = 0, maximum = 1, expression = "" },
		{id = 58, name = "OPTION", minimum = 0, maximum = 1, expression = "" },
		{id = 59, name = "CONTROL", minimum = 0, maximum = 1, expression = "" },						
        {id = 67, name = "*", minimum = 0, maximum = 1, expression = "" },
        {id = 68, name = "-", minimum = 0, maximum = 1, expression = "" },
        {id = 69, name = "+", minimum = 0, maximum = 1, expression = "" },				
} 
